# Site
url: https://vikpe.org
name: Viktor Persson

# Custom settings
custom:
  home_title: vikpe
  description: Coding stuff.
  is_development: false
  github_url: https://github.com/vikpe

# Handling/reading
destination: ./../public
safe: true
ignore_theme_config: true
strict_front_matter: true
include:
  - _pages

exclude:
  - _data

keep_files:
  - assets # generate by gulp, not jekyll

# Plugins
# plugins:
#  - jekyll-redirect-from

# Conversion
markdown: kramdown
incremental: false

# Outputting
permalink: pretty
timezone: Europe/Stockholm

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"

# Markdown Processors
kramdown:
  input: GFM
  hard_wrap: false
