name: Build and deploy

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - name: Install and build site
        uses: withastro/action@v0

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
